### ISSUE TITLE
Parsing Dates

### ISSUE THREAD

**Issue by shinyben** [SilentVoid13/Templater#1007]
Say I have the [quick example](https://silentvoid13.github.io/Templater/#quick-example) set up for my personal journal, and I forgot to make my journal entry for yesterday, 1/24/2023. When I create that entry, the quick example will mistakenly believe I am creating the entry for today, 1/25/2023, and return `< [[2023-01-24]] | [[2023-01-26]] >`. 

To fix this I'm requesting the capability to parse the date from the title. This facilitates the creation of multiple journal notes for past days without having to manually edit each time.

**Comment by welpdx** [comment]
This is a cool function to add but I doubt it can be added soon. This requires extra libraries to parse for different date formats in titles. 
Not sure if there are existing plugins for this but if you want a quick and dirty way to do it in templater, you can refer to this post I made before on the exact same topic: [Getting the date from part of filename](https://github.com/SilentVoid13/Templater/discussions/648) #648

**Comment by Zachatoo** [comment]
The [tp.date.now](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/date-module.html#tpdatenowformat-string--yyyy-mm-dd-offset-numberstring-reference-string-reference_format-string) function takes in a "reference" and "referenceFormat" parameter. You can pass in the title and date format of your title along with an offset (-1 for yesterday, 1 for tomorrow) to get links to yesterday and tomorrow based on the file title instead of today.

```js
[[<% tp.date.now("YYYY-MM-DD", -1, tp.file.title, "YYYY-MM-DD") %>|yesterday]]
[[<% tp.date.now("YYYY-MM-DD", 1, tp.file.title, "YYYY-MM-DD") %>|tomorrow]]
```

**Comment by welpdx** [comment]
@Zachatoo 

I thought that the op wanted the date offset thing as well but later on he mentions:

> To fix this I'm requesting the capability to parse the date from the title.

~welp

**Comment by shinyben** [comment]
@Zachatoo's answer worked for my purposes, thank you. Must've either not read the docs or been confused by the formatting.

**Comment by Zachatoo** [comment]
@shinyben Wanna go ahead and close this issue if this has been resolved?
