### ISSUE TITLE
Moving a File based on tags / frontmatter

### ISSUE THREAD

**Issue by ab-ll** [SilentVoid13/Templater#103]
I think the new templating engine is great, I think I'm trying to extend it further than it is designed to be.

I'd like to create a rename template that takes the frontmatter title and then makes it the title of the file; moved to an appropriate folder based upon the tags and update the alias to include both the old and new name.

If I create a rename template and have a frontmatter title then this works

<% tp.file.rename(tp.frontmatter["title"]) %>

as part of the rename

But trying to do a 
<%* tR += tp.file.content.replace(TOKEN_FOR_NEW_NAME, tp.frontmatter["title"]); %>
doubles up the front matter where I have an alias in the first level that has a TOKEN_FOR_NEW_NAME I'm trying to replace

Ideally something like the following would work 
<% tp.frontmatter.aliases[0] = tp.frontmatter["title"] %>

or

<% tp.frontmatter.aliases.push(tp.frontmatter["title"]) %>

to add the front matter.

Finally, I'd like the rename to have a folder that I can set that is relative to the path.  If I'm using windows and I know the path then I can add a ../ to the front which will go up one level. But as I have nested folders I'd like to have a relative path to the base folder of the vault so I could say make the rename <% tp.file.rename("Concept Notes/" tp.frontmatter["title"]) %> and it would move the folder to that location.  Even better would be if I could use javascript to push the folder into a variable that is then selected by the template.

Anyway, hope this makes sense... thanks for your effort.

**Comment by SilentVoid13** [comment]
Hey @ab-ll, if I understand your message correctly, you want two separate features:
1 - To be able to set new frontmatter values, similar to #109.
2 - Some sort of `tp.file.move` to be able to move files across the vault, based on a relative vault path

Is that correct, or did I misunderstand some parts ?

**Comment by ab-ll** [comment]
Hi, thats correct thanks; also really like the idea of the gallery of templater uses.

**Comment by weeyizhi** [comment]
> Hey @ab-ll, if I understand your message correctly, you want two separate features:
> 1 - To be able to set new frontmatter values, similar to #109.
> 2 - Some sort of `tp.file.move` to be able to move files across the vault, given a relative vault path
> 
> Is that correct, or did I misunderstand some parts ?

I would like to +1 on both of the mentioned features. Especially `tp.file.move`. Since we already have `tp.file.rename`, it makes sense to be able to move files too. I myself main use templater to quickly create files that I tag as a certain 'type'. Being able to move them into a folder for said specific type is very much desirable. As it makes it easier to find all files of a said type.

As OP mentioned, having the ablility to put in relative path from Obsdian's root directory would be very very useful.

**Comment by SilentVoid13** [comment]
@weeyizhi @ab-ll `tp.file.move` has been implemented as of Templater 1.6.0. Pass a vault relative path to move your file to the desired location.

Documentation is at https://silentvoid13.github.io/Templater/docs/internal-variables-functions/internal-modules/file-module

**Comment by luckman212** [comment]
@SilentVoid13 This just keeps getting better! What's next? `tp.breakfast.make()` ?

**Comment by ab-ll** [comment]
thats great - thankyou

**Comment by weeyizhi** [comment]
Amazing!
For those who are not familiar with CLI commands, the move internal function actually moves the file and renames it. As such, if you only want to move the folder without changing name, you need to use `<% tp.file.move("resource/note/anki/"+tp.file.title) %>`. This could be something worth adding into the docs.

I also tested that attempting to move a file into a location where another file with same name exists. It causes templater to say it is not doable. Really great since we won't accidentally replace files.

**Comment by yilu1015** [comment]
> Amazing!
> For those who are not familiar with CLI commands, the move internal function actually moves the file and renames it. As such, if you only want to move the folder without changing name, you need to use `<% tp.file.move("resource/note/anki/"+tp.file.title) %>`. This could be something worth adding into the docs.
> 
> I also tested that attempting to move a file into a location where another file with same name exists. It causes templater to say it is not doable. Really great since we won't accidentally replace files.

This is incredibly helpful! I didn't know I needed to add `tp.file.title` to the file path.
