### ISSUE TITLE
File create_new inserting object in created file

### ISSUE THREAD

**Issue by drakythe** [SilentVoid13/Templater#1045]
-   OS: MacOS Ventura 13.1
-   Templater version: 1.16.0
-   Obsidian version: v1.1.15
-   Templater settings: Template folder location: Templater, Trigger Templater on new file creation: ON,

**Describe the bug**
When using a template that invokes tp.file.create_new() my file is created with expected name and content. But also includes a [object Object] at the top of the file that I cannot seem to be rid of.

**Expected behavior**
[object Object] should not appear in new file.

**Further details**
Template Name: "Create Weekly Task File"
Template content
```
<%tp.file.create_new(tp.file.find_tfile('Weekly Tasks'), 'Weekly Tasks ' + moment().day(0).format("MM-DD-YYYY") + '-' + moment().day(6).format("MM-DD-YYYY"), true)%>
```
Referenced "Weekly Tasks" template:
```
```dataview
TASK
where file.cday >= date(<%moment().day(0).format("YYYY-MM-DD")%>) AND file.cdate <= date(<%moment().day(6).format("YYYY-MM-DD")%>)
GROUP BY file.name
``` // IGNORE ME - this comment is here to assist in github markdown formatting.

#WeeklyTasks

```

Example result:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/1108374/221985380-9c016032-a8f6-4bbf-a670-1f7edc1512d0.png">

Troubleshooting steps taken so far:
- I emptied the referenced template file: Result - same
- Searched another way to insert desired content: Cannot find a way to insert a dataview block as a string, the backticks break the string processing of file.create_new().
- passed "Hello, world!" string into file.create_new() while keeping everything else the same: Result - [object Object] at top of file with expected "Hello, world!" text below.

**Comment by drakythe** [comment]
Continuing to try and debug this myself, I search the Obsidian discord for anyone else using this function and found someone with the exact same problem. There wasn't an answer but someone did respond suggesting the person wrap the call in `console.log()` and see what the object is. I decided to try that myself and bizarrely the `[object Object]` at the top of the file did not end up in the new file.

It gets weirder. When I popped the templater file back open there was now a `undefined` between the closing paren of the create_new method and the closing paren of the console.log. So I can wrap the whole thing in a console log, run it _once_ without getting the extra object at the top of my file, and then the templater breaks.

I am even more confused now.

**Comment by Zachatoo** [comment]
That `[object Object]` is a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).

<img width="429" alt="image" src="https://user-images.githubusercontent.com/6936914/222638823-e8b0fe04-0cdd-4b0e-af06-c67fdea8ed1d.png">

The fix is to use [dynamic commands](https://silentvoid13.github.io/Templater/commands/dynamic-command.html) and the `await` keyword to "wait" for the new file to be created before applying the template. The docs briefly mention that you _may_ need to await it [here](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/file-module.html#tpfilecreate_newtemplate-tfile--string-filename-string-open_new-boolean--false-folder-tfolder), but in your case it's definitely required.

> open_new: Whether to open or not the newly created file. Warning: if you use this option, since **commands are executed asynchronously**, the file can be opened first and then other commands are appended to that new file and not the previous file.

```js
<%*
await tp.file.create_new(tp.file.find_tfile('Weekly Tasks'), 'Weekly Tasks ' + moment().day(0).format("MM-DD-YYYY") + '-' + moment().day(6).format("MM-DD-YYYY"), true)
%>
```

**Comment by Zachatoo** [comment]
Actually, the `await` keyword isn't required, and isn't the issue. The real fix was switching to a dynamic command. This is because interpolation commands (`<% %>`) will "implicitly" return the Promise object, while with dynamic commands (`<%* %>`) you have to specify if you want to return something or not.

**Comment by drakythe** [comment]
I missed the different interpolation command syntax! That did fix it. Thank you!
