### ISSUE TITLE
insert lower case title?

### ISSUE THREAD

**Issue by filmgal** [SilentVoid13/Templater#112]
Is there a way to convert the file title to lower case when using `<%tp.file.title%>?`

Use Case:  I'm using the dataview plugin in one of my templates, and I'm using:
`list from [[<%tp.file.title%>]] or #<%tp.file.title%>` but the tag part (`#<%tp.file.title%>`) needs to be lower case.

I've looked at the User Function section of [this help file](https://silentvoid13.github.io/Templater/docs/user-functions) but I confess I'm not familiar enough with functions to know how to do it myself.

**Comment by SilentVoid13** [comment]
Hey @filmgal, this is possible, you can use `<% tp.file.title.toLowerCase() %>` to make the whole string lower case.
Because Templater is just JavaScript under the hood, and because variables / functions are returning strings, you can use all of the JavaScript functions related to strings.
I'm not asking you to learn JavaScript of course, it's a just a tip for next time: try to search for something like "make string lowercase javascript" or whatever you're searching for, and you'll probably find what you're looking for.
You can also ask a question here if you need help of course.

**Comment by filmgal** [comment]
@SilentVoid13 Thanks so much for the reply. I'm teaching myself javascript as we speak. Fingers crossed I can get by with the basics by year end.
