### ISSUE TITLE
tp.file.create_new doesn't insert the template in the new file

### ISSUE THREAD

**Issue by Phenixis** [SilentVoid13/Templater#1131]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 1.16.0
-   Obsidian version: 1.3.5
-   Templater settings: 
    -  Templater folder location : "0. Datas/Modèles/"
    -  1 template is bugging : "Create New note"

This template contains a unique line :
`<%* tp.file.create_new(tp.file.find_tfile("New note"), "Nouvelle note", true) %>`

This should create a new note containing my template for new note and open it. 

When I execute the template, the note is created, then it opens, the template that should be append to the new file appears and half a second later, disappears. Then, Obsidian select the new note's title to let me change it.

**Expected behavior**
- The creation of the note. [👍]
- The insertion of the template. [👎]
- (if possible only) The selection of the new note's title in order to let me change it.

**Comment by Zachatoo** [comment]
You wouldn't happen to have two notes in your vault called `New note` would you? `tp.file.find_tfile()` will find the first one it can and use that, so if you have another note called `New note` that it finds first and it's empty, then nothing will be inserted into your template.

Likely unrelated, but you should `await` creating the file since that's an asynchronous operation.
```js
<%* await tp.file.create_new(tp.file.find_tfile("New note"), "Nouvelle note", true) %>
```

**Comment by Phenixis22** [comment]
I have only 1 file called"New note", I verified it ! And, I've just tried to put `await` before the command but it changed nothing... It has the exact same behavior : create the note, open it with the template in it, then the template disappear...

**Comment by Phenixis22** [comment]
I am now using this template to create a new note, and have noticed that a few times it works. The template displayed fine in the newly created note and everything was fine.
So, know that my computer is a bit slow and that could be the reason for my problem. I'm not closing the issue since it may be an error in the code, I don't know at all, but my computer's performance may be the reason for the bug.
If you tell me that this command is working for you, so I'll close the issue because it's probably my computer's performance.

**Comment by Zachatoo** [comment]
Can you provide your `New note` template? Maybe it's an issue with that template.

And if there's anything else in your template where you're creating the file, you should provide that full template as well.

**Comment by Zachatoo** [comment]
Marking as removed due to no response from issue author.

**Comment by Phenixis** [comment]
Yeah sorry I changed my `New Note` template so I don't have this problem anymore !

**Comment by Phenixis** [comment]
I just hope this problem happens to no one else
