### ISSUE TITLE
Help needed to fix template using tp.file.clipboard() 

### ISSUE THREAD

**Issue by MaksimZinovev** [SilentVoid13/Templater#115]
First of all, thank you for your hard work. Templater is awesome!

**Context:** 
I am a software tester and I  use Obsidian and Templater plugin for my work. So I was trying to implement automations to speed up some text-based tasks. Please see the description below. Note: I am not a programmer, my apologies for any mistakes in the code.
Scenario 1 - works as expected, text is generated.
Scenario 2 - [object Promise] is printed instead of the generated text.

**Environment:**
- macOS Catalina 10.15.7
- Obsidian v.0.11.13
- Templater 1.3.0

![Screen Shot 2021-04-17 at 9 37 00 am](https://user-images.githubusercontent.com/53397443/115094329-7dbac100-9f60-11eb-98cf-7d9511cfdf0f.png)

**Scenario 1:**
1. Create new template

```
Template-1:

<%* clip =  ("," + tp.file.selection()).split(',').join(' \n- Verify,'); %>
<%* tR += "Generated: \n" + clip  %>
```
2. Create new note "test selected" in Obsidian:

```
text, number, date, boolean, list, m-list 
```
3. Select text in the note.
4. Apply Template-1.
5. Observe output in a note:

```
Template-1:


Generated: 
 
- Verify,text 
- Verify, number 
- Verify, date 
- Verify, boolean 
- Verify, list 
- Verify, m-list 

```
&nbsp;
&nbsp;

**Scenario 2:**
1. Create a new template

```
Template-2:

<%* clip =  ("," + tp.file.clipboard()).split(',').join(' \n- Verify,'); %>
<%* tR += "Generated: \n" + clip  %>
```
2. Create a new note "test clipboard" in Obsidian:

```
text, number, date, boolean, list, m-list 
```
3. Select and copy the text in the note.
4. Click at the end of the line and press Enter.
5. Apply Template-2.
6. Observe output in a note:
```
text, number, date, boolean, list, m-list 
Template-2:


Generated: 
 
- Verify,[object Promise]
```

![templater-issue](https://user-images.githubusercontent.com/53397443/115094668-b6a76580-9f61-11eb-8c5e-a9fba9b90e17.gif)

**Comment by SilentVoid13** [comment]
Hey @MaksimZinovev, first things first, the `tp.file.clipboard` function was moved to a new module, it's now `tp.system.clipboard` as of Templater 1.5.2.

In your 2nd scenario, you are getting a `[object Promise]` as a response because the `tp.system.clipboard` function is an asynchronous function, which means it doesn't return a result immediately like a synchronous function.
You need to explicitly wait for it using the `await` keyword.

This would give the following template in your case:
```
Template-2:

<%* clip =  ("," + (await tp.system.clipboard())).split(',').join(' \n- Verify,'); %>
<%* tR += "Generated: \n" + clip  %>
```
 
Next time you encounter an `[object Promise]` in your results, remember to use the `await` keyword before the function call.
