### ISSUE TITLE
Modifying templates with calculated non-text properties for Obsidian Properties update

### ISSUE THREAD

**Issue by jimjam-slam** [SilentVoid13/Templater#1167]
**Plugin information (please complete the following information):**

-   OS: macOS
-   Templater version: 1.16.0
-   Obsidian version: 1.4.3

Hi there! I have a template that requests a date from the user and fills it into the document frontmatter:

```
<%*
  const due_date = await tp.system.prompt("When's the package due? (YYYY-MM-DD)",
	  tp.file.creation_date("YYYY-MM-DD", 56))
%>
---
due: <% due_date %>
status: ⭕ Not started
---

**Package folder link:**

## 📖 Definitions

## 📚 Data sources

## 📋 Tasks

```

Since I've updated to Obsidian 1.4.3, which includes the new Properties interface, this doesn't work as it did previously. For example, here's a template I've just instantiated:

<img width="1004" alt="image" src="https://github.com/SilentVoid13/Templater/assets/6520659/3f0fa753-a711-4510-9ef7-1a62aa8346d9">

Although I had the opportunity to provide a date for the prompt, the properties were lost entirely.

I can modify this template to include the "status" property on the template itself, and that appears to be added to the instantiated template:

<img width="635" alt="image" src="https://github.com/SilentVoid13/Templater/assets/6520659/83b9f000-0c37-4ad4-a8c5-09ba607796b3">

<img width="661" alt="image" src="https://github.com/SilentVoid13/Templater/assets/6520659/b16e76bb-4289-432d-a303-a1e87cb23386">

I can also create a text type "due_date" property and add Templater code to that, and that works:

<img width="365" alt="image" src="https://github.com/SilentVoid13/Templater/assets/6520659/15d62cfa-58f4-40f5-a87f-39135f1dd320">

<img width="328" alt="image" src="https://github.com/SilentVoid13/Templater/assets/6520659/bdcc39c0-e5b6-48b6-b876-0c6e20485305">

But I can't use the Date type for the due_date property, because it won't allow me to add the Templater code (because it validates the input as a date).

Is there a way I can calculate the date in the body and then add the calculated property to the frontmatter from there? I know there is `tp.frontmatter` for _getting_ frontmatter, but I don't know if there's a way to dynamically _set_ non-text frontmatter now that the new interface exists.

**Comment by Zachatoo** [comment]
If you switch into source mode (using the `Toggle Live Preview/Source Mode` command), you will see that all your frontmatter is actually there, it just isn't being picked up by Obsidian as "properties." This is because your frontmatter isn't on the first line of the note.

You can update your template to include [whitespace control](https://silentvoid13.github.io/Templater/commands/whitespace-control.html) so your frontmatter is at the very top of the file instead of one line below the top of the file.

```
<%*
  const due_date = await tp.system.prompt("When's the package due? (YYYY-MM-DD)",
	  tp.file.creation_date("YYYY-MM-DD", 56))
-%>
---
due: <% due_date %>
status: ⭕ Not started
---

**Package folder link:**

# 📖 Definitions

# 📚 Data sources

# 📋 Tasks

```

This will also treat your date metadata as a "date" type, as long as you haven't overridden it in your `.obsidian/types.json` file.

---

There does appear to be a bug where if you use the `Templater: Open Insert Template Modal` command, the properties won't show in the note until you switch to another note and back, but they will show immediately in the file properties view, which you can view with the `Properties: Show file properties` command.

All the other Templater commands and folder templates appear to work.

**Comment by jimjam-slam** [comment]
Ah, amazing! I'll give this a whirl today. Thanks very much!

**Comment by jimjam-slam** [comment]
Yes, that works! Thanks! 😊
