### ISSUE TITLE
Date variables are not updating to the current system time

### ISSUE THREAD

**Issue by sisyphus-prime** [SilentVoid13/Templater#1256]
**Plugin information (please complete the following information):**

-   OS: Windows 11 Home
-   Templater version: 1.18.1
-   Obsidian version: v1.4.16
-   Templater settings: 

**Describe the bug**
Calling date-time functions from within a Templater function are returning the same, incorrect time in minutes relative to system time. The minutes are fixed at MM = 12. HH increments to the current hour with MM = 12 always. 

Functions tested:
- tp.date.now()
- tp.file.creation_date()
- moment().format() 

As I was testing, I noticed two additional things: (1) Trying to display the time date stamp as 24h within YAML frontmatter shows up as 12h and (2) triggering the templates:insert-current-time prints the correct current system time.    

**Expected behavior**
Current system date-time printed in the specified format.

**Screenshots**
All screenshots were taken immediately after triggering my test template.

When I first noticed the discrepancy between the current system time and the time printed from the template variable.
![Screenshot 2023-12-01 093307](https://github.com/SilentVoid13/Templater/assets/151857782/08770705-6924-4214-85bb-b0f3c62d1349)

Testing all three functions and then printing templates:insert-current-time. MM = 12 but HH has changed to current system hour for the template variables but the insert-current-time variable appears to track system time.. 
![Screenshot 2023-12-02 152405](https://github.com/SilentVoid13/Templater/assets/151857782/dc584587-12e9-4bbe-abbe-ccc9be0e865e)

**Additional context**

**Comment by Zachatoo** [comment]
Sounds like you're using `MM` instead of `mm` for displaying minutes. `MM` is for months, which is why it's always 12 (December). See [momentjs docs](https://momentjs.com/docs/#/displaying/) for details.

---

> Trying to display the time date stamp as 24h within YAML frontmatter shows up as 12h

This is not something Templater can control. How the `date` type property value displays is controlled by the OS (see [this feature request](https://forum.obsidian.md/t/properties-let-the-user-customize-the-way-dates-times-are-displayed-independently-from-os/64139) that requests Obsidian changes how that works).

---

Going to mark as closed, since the first is working as intended and the second is outside the scope of what Templater can do. Please comment here if I'm making any incorrect assumptions and I can reopen this bug report. Thanks!

**Comment by sisyphus-prime** [comment]
Thank you for responding and teaching me about Date/Time codes.

----
Paul Ramer, CAIA, CFA
***@***.***
(303) 359-4192
