### ISSUE TITLE
File rename template no longer working since recent update.

### ISSUE THREAD

**Issue by rudyolph** [SilentVoid13/Templater#1316]
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 2.1.3
-   Obsidian version: 1.5.3
-   Templater settings:

**Describe the bug**
Ever since I installed the recent Templater release my file rename template isn't working.  

Each of my notes has a "button" it is like this:  
```button
name Done!
type append template
action Rename Done
color green
```

I have a template called Rename Done in my templates folder which has this following in it:
<% await tp.file.rename(tp.file.title + " - ✔") %>

What used to happen is when I click the button in my note it would rename the current note file I'm in to include the - ✔ at the end of the filename.  What happens now...is it just renames my template file to:  undefined - ✔ and does not change the name of the note I'm in at all.

**Comment by Whattheblah12** [comment]
i have same problem, i dont know if its a button issue or templater

**Comment by rudyolph** [comment]
I'm hoping the recent bugfix change has something to do with it and that it is an easy fix.  I rely on this functionality heavily.

"modifying current file immediately after inserting template causing file content conflicts ([b9112fa]"

**Comment by rudyolph** [comment]
Looks like Buttons also had a release last week and found this issue reported:

https://github.com/shabegom/buttons/issues/210

**Comment by Whattheblah12** [comment]
> Looks like Buttons also had a release last week and found this issue reported:

yes it is a buttons issue, i looked on their github for this issue too, and unless you want to rewrite your buttons you need to go into the previous version of buttons

buttons changed the way it works so that it "activates" the templater code FIRST before running the rest of the button code, i.e it applies all the templater code to the template if you did not code the button around this fact

**Comment by Zachatoo** [comment]
Even though this isn't a Templater bug, I'm going to recommend a solution that I'm betting will work from FeralFlora on the Obsidian Discord.

> I find that the best way to run Templater via buttons is to assign the template to a hotkey, so it becomes available in the command palette. This way, you can run the template through buttons as a command, like so:
> ```
> name Update literature note
> type command
> action Templater: Insert 07 - Bins/Templates/runImport.md
> class update-lit-note
> ```
> The action is written like what you see in the command palette.

https://discord.com/channels/686053708261228577/1175184210609328229/1180515931504525344

Let me know if triggering Templater with a `command` button instead of an `append template` button works.

Going to mark this as closed since it isn't a Templater bug.

**Comment by shabegom** [comment]
Buttons 0.5.1 should fix this issue. It was a shabegom problem.
