### ISSUE TITLE
Incorrect date calculation

### ISSUE THREAD

**Issue by thomasxin1994** [SilentVoid13/Templater#1355]
Plugin information:
OS: win11
Templater version: 2.2.3
OB version: 1.5.12

Describe the bug
When calculating the date of a week based on the week number, it incorrectly returns the corresponding date of the following week.

Screenshots
this is my templater:
```
<%*
let titleDate = tp.file.title;
let yearWeek = titleDate.substring(7);
let [year, week] = yearWeek.split("-");
let saturday = moment().isoWeekYear(parseInt(year)).isoWeek(parseInt(week)).day("6");
let this_saturday = saturday.format("YYYY-MM-DD");
let last_saturday = window.moment(saturday, true).add(-7, "days").format("YYYY-MM-DD")
_%>
```
Result:
input: file title= Weekly 2024-17
return: saturday= Sat May 04 2024 23:09:32 GMT+0800
           this_saturday= 2024-05-04
           last_saturday= 2024-04-27

**Comment by Zachatoo** [comment]
This doesn't appear to be a bug with Templater, rather a misunderstanding of how moment works.

Here are a few ways to get the Saturday for the current ISO week based on your file format.

```js
// Supplying moment with a format
let saturday = moment(tp.file.title, "[Weekly ]YYYY-WW").day("6");
let this_saturday = saturday.format("YYYY-MM-DD");
let last_saturday = moment(saturday).add(-7, "days").format("YYYY-MM-DD");
```
```js
// Using tp.date.weekday with a format
let this_saturday = tp.date.weekday("YYYY-MM-DD", 6, tp.file.title, "[Weekly ]YYYY-WW");
let last_saturday = tp.date.weekday("YYYY-MM-DD", -1, tp.file.title, "[Weekly ]YYYY-WW");
```

Got the format from the [moment docs](https://momentjs.com/docs/#/displaying/).

Going to mark as closed since if there is a bug, it would be with moment, not with Templater.
