### ISSUE TITLE
Error: Failed to List Templates, No Template Folder Configured

### ISSUE THREAD

**Issue by ansuhayda** [SilentVoid13/Templater#1373]
**Plugin information (please complete the following information):**

-   OS: Windows 11
-   Templater version: 2.3.1
-   Obsidian version: 1.5.12
-   Templater settings: Template folder location:  Plugins/Templater

**Describe the bug**
I just installed Templater today and I'm having some trouble setting it up.  I have a folder for Plugins with a subfolder for Templater.  I entered the path into the Templater settings as Plugins/Templater but when I try to insert a template into a note I get this error, "Failed to list templates.  No template folder configured".  I tried moving the Templater subfolder out of the Plugins folder so that it would no longer be a subfolder, but that didn't work either.  

What's strange is I also have a template I created a hotkey for located at Plugins/Templator/BASH Script Table and when I go to insert this template, it works just fine.  

So why can't templater find the folder I created for it but it can find a specific template that exists within the templater folder?  Maybe I'm doing something wrong, I don't know.  Some help would be much appreciated though!

**Comment by kid38** [comment]
Had this issue too. Turns out you need to also select a folder in Options → Core plugins → Templates

**Comment by Zachatoo** [comment]
Are you both using the correct command for inserting a template? It should be `Templater: Open insert template modal`, not `Templates: Insert template`. I recommend disabling the core Templates plugin to avoid this confusion.

**Comment by nezlok** [comment]
Hm, I'm also now no longer having templater follow when I create a file in a folder already stipulated by templater.  Having the core template enabled or disabled doesn't fix it, nor does stipulating a folder in the core template plugin.  Something changed...

**Comment by Zachatoo** [comment]
> when I create a file in a folder already stipulated by template

@nezlok Are you referring to the "folder templates" setting, or the "template folder location" setting? I believe this issue is regarding the "template folder location" setting if I'm not mistaken. 

> it feels as if it doesn't know which folder its in, and just creates a new file in the root rather than from where you are

I don't believe there's a Templater setting for the default location for new files, are you maybe looking for "settings - files & links - default location for new notes"?

Overall I'm a bit confused as to what you're talking about, an example would be helpful.

**Comment by nezlok** [comment]
Ah, apologies.  Yeah, kind of lacking in terms of the details.

So, I'm using Periodic Notes, which creates a file structure to store daily notes (doing the same for journal entries which seems to stuff from the same issue, but I'll keep it just on this one for the example)

![Screenshot 2024-05-12 162831](https://github.com/SilentVoid13/Templater/assets/23189658/cd3647b2-d037-4d3c-824f-e6c60e5299bd)

Here you can see I forgot to create yesterday's note, so the file is missing.  Normally, in my daily note template, it has entries for yesterday and tomorrow, and I can just click on 'yesterday', and because I'm in the folder listed in templater as a daily note, it would use the template to spawn the new file with the right template, in the same folder.

![image](https://github.com/SilentVoid13/Templater/assets/23189658/746243e4-8831-4884-a328-98cebf6206c0)

However currently when I click the Yesterday link, it will create the entry in the root folder, and I imagine because its not in the right folder, it doesn't apply the template.

![image](https://github.com/SilentVoid13/Templater/assets/23189658/cc871c31-4a6f-4835-80b2-4c211f768535)

It was working for... man I feel like a year, but to be fair I don't often run into this situation so it could have been awhile since it hasn't be working.  Some nice people are helping me look on the discord if I can actually specify the folder structure in the template as a workaround, but I imagine this ... should be working.

Let me know if this is more clear, or if this isn't a templater problem at all

**Comment by Zachatoo** [comment]
@nezlok I don't believe that has ever worked, you need to specify the path in the link, otherwise Templater will always default to the default path defined in the setting I brought up earlier. Templater doesn't know that you have Periodic Notes installed or that that link is supposed to go in a specific folder. I've had to include the path in my links for 2+ years.

This isn't related to this issue, I'm in that discord and am happy to discuss it further there or in a separate issue :)

**Comment by nezlok** [comment]
Hrm, interesting.  Ok, will continue in the discord.  Thanks for the insight o7

**Comment by Zachatoo** [comment]
@ansuhayda Does my recommendation [here](https://github.com/SilentVoid13/Templater/issues/1373#issuecomment-2105985239) resolve this issue?

**Comment by Zachatoo** [comment]
Closing due to no response.
