### ISSUE TITLE
main.js missing

### ISSUE THREAD

**Issue by ebah80** [SilentVoid13/Templater#1377]
Hi,
Templater community plugin installed succesfully but can't enable and use it.

I think main.js is missing after installing Tempalter plugin latest version 2.3.1
Under:
- [...]\.obsidian\plugins\templater-obsidian
I have only:
- manifest.json
no directories or other files ...

**Comment by Zachatoo** [comment]
It's definitely not missing in the release, see below. If it's a bug, it's not with Templater. Try uninstalling and installing again.

https://github.com/SilentVoid13/Templater/releases/tag/2.3.1

**Comment by ebah80** [comment]
Apologize, on my work laptop (windows with admin rights, obsidian vault is hosted on a Google Drive folder) it's not working while it's working perfectly on my personal laptop (linux Fedora 40).
On monday I will gather some info from my work laptop and share.
Right now I would bet that I have some Firewall/ZScaler issue.
Maybe an external endpoint is contacted during the plugin  installation ...

**Comment by Zachatoo** [comment]
As far as I know, Templater only contacts external endpoints when using a [web module](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/web-module.html), otherwise it's completely offline. No idea if Obsidian does anything special other than contacting GitHub to download the plugin.

Going to mark this as closed since it's likely not related to Templater, but we can keep discussing in here if needed!
