### ISSUE TITLE
bug: app.workspace.getLeaf().openFile() replaces content in a note if called without "await"

### ISSUE THREAD

**Issue by erazlogo** [SilentVoid13/Templater#1384]
**Plugin information (please complete the following information):**

-   OS: MacOS Sonoma 14.5
-   Templater version: 2.3.2
-   Obsidian version: 1.6.1
-   Templater settings: [Templater folder location: "meta/templater"]

**Describe the bug**
Since the last update, this script replaces the content in the note "advanced research notes search.md" with whatever note is open at the time I trigger the script via command palette:

```
<%*
const file = app.vault.getAbstractFileByPath('meta/dataview/advanced research notes search.md');
app.workspace.getLeaf(false).openFile(file); 
app.commands.executeCommandById('obsidian-focus-mode:toggle-super-focus-mode');
-%>
```

This script--"await" added before app.workspace.getLeaf--works as intended, opening "advanced research notes search.md" in a super focus mode:

```
<%*
const file = app.vault.getAbstractFileByPath('meta/dataview/advanced research notes search.md');
await app.workspace.getLeaf(false).openFile(file); 
app.commands.executeCommandById('obsidian-focus-mode:toggle-super-focus-mode');
-%>
```

It seems that even if the "await" is required before app.workspace.getLeaf, replacing content is not what should happen here. It could be that the other plugin is to blame but it's odd that it works in Templater with "await" but not without.

**Expected behavior**
Previously, the script without "await" worked to open "advanced research notes search.md" in a super focus mode.

**Comment by Zachatoo** [comment]
[`getLeaf`](https://docs.obsidian.md/Reference/TypeScript+API/Workspace/getLeaf_1) doesn't return a `Promise`, so the `await` isn't really doing anything. Seems more like a race condition between Obsidian opening the file and the obsidian-focus-mode plugin trying to access the active file.

Closing as I doubt this is related to Templater, and since you aren't using Templater APIs, there's no change we can make on the Templater side to resolve this.
