### ISSUE TITLE
Strip ZID from filename when using tp.file.title

### ISSUE THREAD

**Issue by thoresson** [SilentVoid13/Templater#176]
**Is your feature request related to a problem? Please describe.**
All notes in my Obsidian vault use a numeric Zettelkasten ID as a prefix, based on the date and time when the file was created: YYYYMMDDHHMM. The ZID is followed with a space and then the "real" filename. So, a note created right now about this feature request would be _202104300909 Feature request for Templater plugin_.

In my templates, I frequently use <% tp.file.name %>. But within my actual notes, I don't want the ZID. This means I have to do a lot of manual editing, removing the ZID in my notes.

**Describe the solution you'd like**
A new function for the File module, something like <% tp.file.shortname %>, with a user defined setting for how many characters the function should throw away from the beginning of the filename. Set to 13 would in my case remove the ZID and the space.

**Comment by SilentVoid13** [comment]
Hey @thoresson, this is already possible! Because Templater is Javascript under the hood, you can use any JS string manipulation function on your variables.
In your case, this would give the following:

```
<% tp.file.title.slice(13) %>
```

Tell me if this works like you want it to work.

If in doubt in the future, try asking in the Github discussion section, under the help category or in the Obsidian discord plugins section, there are always people willing to help (You can also ask here, but I'm not the fastest to respond)
