### ISSUE TITLE
Leveraging 'moment js' for 'X days ago'

### ISSUE THREAD

**Issue by MartynKeigher** [SilentVoid13/Templater#181]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I have Templater working just fine in its current design, and I can add the date of when a note was both created and last updated. What I would like to do though is add the string `(## days|months ago)` or `##` is the forvere changing number of days (and\or months) ago the page was created\updated.

e.g: of what i'm after in full:
`Date Created: April 22nd, [Thurs], 2021 (9 days ago)`

**Describe alternatives you've considered**
N/a

**Additional context**
I have tried a bunch of different syntax to get this to work. So it's me not getting it right, or its just not implemented yet??

Thanks! 
://mk

**Comment by SilentVoid13** [comment]
Hey @MartynKeigher this is now possible as of Templater 1.6.0 with dynamic commands.

In your use case, this would give:

```
(<%+ moment().diff(tp.file.creation_date(), "days") %> days ago)
(<%+ moment().diff(tp.file.last_modified_date(), "days") %> days ago)
```

To get it correct in the preview mode. If you want it to be correct in edit mode too, Templater can't do that, because once a command is replaced with plain text, there are no ways to keep track of this replaced text.

Documentation at https://silentvoid13.github.io/Templater/docs/commands/dynamic-command
