### ISSUE TITLE
Dynamic commands can't be formatted

### ISSUE THREAD

**Issue by zimt28** [SilentVoid13/Templater#204]
**Plugin informations (please complete the following information):**
 - OS: macOS 10.15.7
 - Templater version: 1.6.0
 - Obsidian version: 0.11.13
 - Templater settings: default

**Describe the bug**
Dynamic commands don't seem to respect formatting rules:
``# <%+ tp.file.title %>``
``** <%+ tp.file.title %> **``
Both examples don't return formatted output, just the plain title.

**Expected behavior**
Formatting should be kept, the plugin probably needs to run before the markdown renderer (this would also allow something like `<%+ "# " + tp.file.title %>`).

**Comment by metruzanca** [comment]
I noticed something similar with a template I'm working on that generates shields.io image links from tags, but instead of the markdown image links being rendered in the markdown they're just being treated as text.

With: 

User script: https://gist.github.com/metruzanca/71df2d19fdf29f971909a524b6853669

Obsidian Note: 
```md
---
tags:
- frontend
---
`<%+ tp.user.shields(tp) %>`
```

Expected: 
![image](https://user-images.githubusercontent.com/32832892/117697744-18ef3100-b1c3-11eb-91b2-a8e05167503b.png)

Actual: 
![image](https://user-images.githubusercontent.com/32832892/117697348-a8e0ab00-b1c2-11eb-895a-45441572d956.png)

---
@zimt28 
> the plugin probably needs to run before the markdown renderer 
yeah, I believe this is indeed the issue, as in my case its like the text is being simply appended to the markdown rendered to html.

Would be pretty awesome if Silent is able to put it before as that would open up many possibilities.

**Comment by JeppeKlitgaard** [comment]
I have run into this as well. It seems to also break the metadata format:

![image](https://user-images.githubusercontent.com/1814611/119238869-97de5500-bb45-11eb-8644-2e46b049ae15.png)

**Comment by SilentVoid13** [comment]
Hey @zimt28 @metruzanca @JeppeKlitgaard, thanks for the report this should now be fixed as of Templater 1.7.0.
Update and tell me if this works now for you!

**Comment by JeppeKlitgaard** [comment]
@SilentVoid13 

I can't seem to get dynamic templates working in the frontmatter still. I am aware that caching is a known issue, but even using the 'tricks' that would usually update the cache doesn't make it render.

This is on 1.7.0

![image](https://user-images.githubusercontent.com/1814611/119243030-9459c680-bb63-11eb-801d-eacc22b1a5d4.png)

This should possibly be a new issue.

**Comment by SilentVoid13** [comment]
@JeppeKlitgaard You're right but that's actually because obsidian transforms the YAML block into HTML for rendering weirdly. 
It splits the `<%+ tp.date.now() %>` string into two HTML tags, one with `<%+ tp.date.now() %` and the last one with `>`.
This works fine if you put the Templater command into quotes as a string though: `"<%+ tp.date.now() %>"`.

This isn't exactly a Templater bug, but I'll try to check if I can bypass that behavior somehow.

**Comment by JeppeKlitgaard** [comment]
@SilentVoid13 Thank you for being so helpful!

That fix works perfectly! Might be worthwhile to add it to the docs?

**Comment by welpdx** [comment]
> This isn't exactly a Templater bug, but I'll try to check if I can bypass that behavior somehow.

Hey @SilentVoid13, can you give us an update on this sometime? Thank you

**Comment by syepes** [comment]
@SilentVoid13 Is this always the case what we have to use the quotes? Its just that the rendered result contains the quotes :-)

it would be great if we could remove the quotes form the output
