### ISSUE TITLE
Trigger templater on new file creation: executes templates in template folder on Sync

### ISSUE THREAD

**Issue by zsviczian** [SilentVoid13/Templater#244]
I am using Obsidian sync between 4 devices.
When a new template is synced to the other 3 devices, the template runs when first synchronized.
Trigger templater on new file creation should ignore the template folder.

**Comment by JeppeKlitgaard** [comment]
Or better, a config option with a list of directories to ignore?

**Comment by zsviczian** [comment]
absolutely!

**Comment by JeppeKlitgaard** [comment]
I was just messing around with some Templater, and I think this would be most intuitively implemented along with another very useful feature:

Per-folder based new file creation templates:
- Allow specifying which template to insert and trigger based on folder
- This should be recursive (`/a/b/` inherits from `/a/`)
- Deeper folders should have priority
- if `/a/` and `/a/b/` both have a template set `/a/b/` has priority

This allows for:
- A global default template (simply set `/` -> `/templates/default.md` or something like that
- Exclusions (set `/templates/` to `/templates/blank.md`, which would be an empty file)
- Per folder templates: `/people/` and `/cars/` can have different templates.

@SilentVoid13 should I create a separate issue for this?

**Comment by Moonbase59** [comment]
> Per-folder based new file creation templates:
> 
>     * Allow specifying which template to insert and trigger based on folder
> 
>     * This should be recursive (`/a/b/` inherits from `/a/`)
> 
>     * Deeper folders should have priority
> 
>     * if `/a/` and `/a/b/` both have a template set `/a/b/` has priority

This is how we decided to do it in the _Hotkeys for Templates_ plugin, see https://github.com/Vinzent03/obsidian-hotkeys-for-templates/issues/7

**Comment by JeppeKlitgaard** [comment]
> > Per-folder based new file creation templates:
> > ```
> > * Allow specifying which template to insert and trigger based on folder
> > 
> > * This should be recursive (`/a/b/` inherits from `/a/`)
> > 
> > * Deeper folders should have priority
> > 
> > * if `/a/` and `/a/b/` both have a template set `/a/b/` has priority
> > ```
> 
> This is how we decided to do it in the _Hotkeys for Templates_ plugin, see [Vinzent03/obsidian-hotkeys-for-templates#7](https://github.com/Vinzent03/obsidian-hotkeys-for-templates/issues/7)

I am not sure why, but I can't get recursive defaults to work consistently with `hotkeys for templates`.

I also think it would make more sense for this feature to be part of `Templater`, rather than `hotkeys for templates`, but that might just be me.

**Comment by LaP0573** [comment]
In addition to this bug report, and let me know if I should create a separate issue for this, it would be great having an option to ignore Sync newly created files.

I've got a template that opens the suggester (and does a ton of other things based on that) whenever a new file is created, as a means to say "okay this file is a daily note, this one is a meeting" (and I toggled the "when a new file is created" option so that it also runs when a note is created through clicking on a link), but it also triggers whenever a file is synced via Obsidian Sync, which makes it unusable unfortunately

**Comment by Moonbase59** [comment]
@JeppeKlitgaard Yes, it seems a bug in Hotkeys for Templates, please open an issue over there, I’ll then chime in.

I only mentioned the Hotkeys for Templates here so that we know others are doing the same, and I don’t want users having to learn different behaviour, and plugins somehow to "keep in sync".

Yes I agree that it should be in Templater, and actually use _both_. Which opens a new can of worms, because both hook into the new file event chain, and _both_ templates are included.

Auto-reacting to system events can pose a lot of unthought-of new problems, like many now experience: Due to how synchronization tools work (probably keeping backups and making new files), it looks like a "new file" event. This might turn out to be not easy to handle.

**Comment by SilentVoid13** [comment]
Hey @zsviczian, updated Templater to ignore the templates folder when detecting a new file creation event. I might add an option to ignore multiple folders later.

**Comment by SilentVoid13** [comment]
@LaP0573 I agree that ignoring synced files would be the best way, but I have no way to know **how** the file was created when the new file creation event is fired. Maybe some future obsidian API updates could add context informations about this.

**Comment by Moonbase59** [comment]
Re: Synced files: But … you’ll never know, because people use other sync tools like Syncthing, too. (My Syncthing syncs ~1.3 million files between several machines, flawlessly since many years, so I didn’t see the need to go for yet another syncing tool.)

**Comment by shabegom** [comment]
Closing as stale. If still a problem please open a new issue.
