### ISSUE TITLE
How to use Typescript instead of Javascirpt

### ISSUE THREAD

**Issue by tami5** [SilentVoid13/Templater#262]
Hey there, 

Thanks for this awesome plugin that feels like a more like a scripting edition to Obsidian rather than a simple templater.

Coming from static languages, I find a bit wired writing code without type checking and compile time errors :D. 

So I wonder if it's possible to somehow write my templates (scripts) in typescript and better yet distribute lines of code to their own files (did I mention I'm new to js/ts language) 

Thanks :D

**Comment by SilentVoid13** [comment]
Hey @tami5 Typescript is just a superset of Javascript that adds strong typing, among other things. Ultimately typescript gets compiled to javascript, it's just a superset. 
What you can do is write your template in Typescript and compile it to a commonJS javascript file (just like obsidian plugins) using the `tsc` compiler for example. You can then load that js file, but the script file needs to be in javascript, because loading typescript at runtime isn't supported atm (at least not that I know of)

**Comment by tami5** [comment]
Thanks @SilentVoid13 

How about import another commonjs file within templater directory . my single js file is getting too large. 

I'm thinking if having a subdirectory in templater that compiles a group of files into one file in root. 

hmmm
