### ISSUE TITLE
Week Numbers are off by a week

### ISSUE THREAD

**Issue by dummifiedme** [SilentVoid13/Templater#273]
**Plugin informations (please complete the following information):**
 - OS: Windows 10
 - Templater version: 1.8.1
 - Obsidian version: 0.12.5
 - Templater settings: 
  
![image](https://user-images.githubusercontent.com/68785729/123625432-5ec48f00-d82d-11eb-9fab-d2f350a8aa34.png)

**Describe the bug**

The date function is behaving unexpectedly. Displays wrong week number for the dates. If you check the image, the date is 28 June and it is in the week 27, while templater gives out 26th. A week back! And I have been facing this since more than a month. I just made my templates around the bug (adding 1 or -1 weeks)
- Also, I have tried for days in the mid-week and still the same error.
![image](https://user-images.githubusercontent.com/68785729/123625908-e01c2180-d82d-11eb-8d34-cf03bb04af8a.png)

**Expected behavior**
To display correct week number.
![image](https://user-images.githubusercontent.com/68785729/123626287-4e60e400-d82e-11eb-8c14-1b02d0e97e17.png)

**Additional context**
Note: I am using Monday as my first day of the week. Both in the system-wide settings and in the calendar plugin.

**Comment by welpdx** [comment]
This is not an issue with Templater but with the Calendar plugin. 
Templater's week number is calculated according to the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard. The week number right now is [26](https://weeknumber.com/).
The default setting in the Calendar plugin is calculated "[using the locale week number (rather than the ISO week number)](https://github.com/liamcain/obsidian-calendar-plugin/issues/140#issuecomment-780017453)".
I recommend you use the ISO-8601 standard instead of using the locale week number.  You can switch to ISO-8601 by going to Settings -> Calendar -> Override locale: -> select `en=GB`. See [liamcain](https://github.com/liamcain)'s [comment](https://github.com/liamcain/obsidian-calendar-plugin/issues/97#issuecomment-753557567).

This "might" mess up your weekly notes, but I think the switch is worth it.

**Comment by dummifiedme** [comment]
@welpdx, thanks!
And I am sorry I raised another issue. I did try to search it out but it never came across in search. 

Switched to en-gb :)

**Comment by welpdx** [comment]
NP! I'm happy to be of help! :D
