### ISSUE TITLE
<% dynamic command type

### ISSUE THREAD

**Issue by KjellConnelly** [SilentVoid13/Templater#284]
I have a template that should insert certain daily tasks based on what day of the week it is:

```markdown
## Daily Tasks
<% tp.user.getRecurringTasks(tp) %>
```

For now, if it's Monday, it should return a task to take out the garbage. Otherwise, should not do anything.

I'm using `<%: Raw display command`. But the problem is that it ALWAYS adds a new line, even if my javascript returns undefined, a task: `return "- [ ] Take out Garbage"` or doesn't return anything.

I also tried `<%*: JavaScript execution command`, but this fails as well because it never returns anything.

Is there a way (and if not, can we make this possible) to dynamically (through what Javascript returns) return text (or no text) through a function without the new line at the end? I like the idea of having a new line added by default, except when nothing is returned:

```javascript
function getRecurringTasks(tp) {
   ...
   if (date == "Monday") {
      return "- [ ] Take out Garbage"
   } else {
      return undefined // or null, or just return, or no return.
   }
}
```

**Comment by SilentVoid13** [comment]
Hey @KjellConnelly, the raw display command doesn't add a new line.

If you use the following template for example:

```
## Daily Tasks
<% tp.user.getRecurringTasks(tp) %>
- [ ] Test1
- [ ] Test2
```

It will add a newline because there is a newline at the end of `<% tp.user.getRecurringTasks(tp) %>` **in the file**, Templater doesn't add this newline.

However, if your function doesn't output anything, the newline will still be here. To remove it you can use Templater whitespace control commands: https://silentvoid13.github.io/Templater/docs/commands/whitespace-control

This means you can change `<% tp.user.getRecurringTasks(tp) %>` to `<% tp.user.getRecurringTasks(tp) -%>`.
This will remove the newline placed **after** the command.

In your function just add a newline manually since the newline from the file is removed:

```js
function getRecurringTasks(tp) {
   ...
   if (date == "Monday") {
      return "- [ ] Take out Garbage\n";
   } else {
      return "";
   }
}
```

and you should be good!
