### ISSUE TITLE
Ideas to improve extensibility

### ISSUE THREAD

**Issue by liamcain** [SilentVoid13/Templater#3]
Hi, very cool plugin. I jotted down some ideas after playing with it for a bit. Let me know what you think!

## Ideas

- In addition to having people submit internal templates to this repo, I think it would be nice if this plugin would just look for javascript files that I could add from my local. So there could be a template dir and a tags dir.
  - This could be a lot more flexible than the bash commands. (While I could achieve the same effect by adding bash commands to call js scripts, that seems like a lot of misdirection)
- Any reason why you prefixed mustache tags with `templater_`? Is that just to avoid clashing with user defined tags?
- I think it would be nice to allow passing args within the replace string, similar to how the built-in templates work. Here's the un-minified version of how Obsidian handles date/time: https://github.com/liamcain/obsidian-calendar-plugin/blob/master/src/template.ts. Each tag could get passed the additional args and choose how to handle them.

## Small Nit
- `internal_templates_map` probably doesn't need to include the {{mustaches}}, you could just add them in the replacer function.

**Comment by SilentVoid13** [comment]
Hey, thanks a lot for the feedback !

I completely agree with all of your ideas, and i will use this post to explain what are my ideas for the future of this plugin.

For the arguments, i had the same exact idea. I think in the future users will be able to pass a list of args to the internal template, and i will pass that list to the internal template function handling this. This will allow internal templates to be way more dynamic. Thanks for the code, that will come handy when i develop this functionality !

Your idea of being able to call some local javascript files is very interesting, and could make this plugin way more scriptable than what it is in its current state. I'll keep this idea in mind for the future.

Concerning the internal templates, I don't think the current way to add new internal templates is really extensible and sustainable. This plugin is really in a beta state and I will probably refactor the way internal templates can be added later.
I was thinking of maybe declaring an interface, where one would have to create a class that extends this interface in order to develop a new internal template.

For the prefixed tags, they are indeed to prevent conflicts with user defined templates, and to recognize internal plugins easily. I could maybe change this to something shorter in the future.

For the `internal_templates_map`, I added the mustaches here because I don't want them to be mandatory, if someone wants to develop a new internal template that can be matched with the tag `[[<template>]]`, they can.

**Comment by LambdaDriver** [comment]
First, massive thanks for your great work on this plugin @SilentVoid13 and to @liamcain for the calendar and periodic notes plugins. My primary use is to combine these for daily, weekly, and quarterly note templates. 

I'm attempting to create a "pretty" date title for my notes generated from the templates, but the note won't always be generated from the template on the same day as the note. (e.g. if I'm planning my day the night before). Is there something I'm missing where that info would be exposed?

Along these lines, what are your thoughts on adding environment variables containing metadata of the new note, workspace, vault, and front-matter.

If I can find some time I'll spike this and send a pull request to review, but wanted to get your thoughts first in case I'm barking up the wrong tree.

**Comment by liamcain** [comment]
I think with the new version, this issue can be closed. Nice work @SilentVoid13!
