### ISSUE TITLE
Retain Folds

### ISSUE THREAD

**Issue by uwidev** [SilentVoid13/Templater#329]
Would it be possible for Templater to remember and retain folds from a template?

I have a daily note that contains filters of queries from the Tasks community plugin. I have two sets of queries: query by due date and query by priority, both of which are under their respective header text (and can be folded). With both of them unfolded, they show redundant information (tasks appear twice), which is why I only have one unfolded at any given time. 

With the way Templater works at the moment, however, when inserting nothing is folded (the template itself is folded). So whenever I create a daily note, I have to manually fold the redundant headers so I can only see relevant information.

**Comment by kevboh** [comment]
Also interested in this, fwiw.

**Comment by liamcain** [comment]
While not a part of Templater core, this is now possible if you use the [Creases plugin](https://github.com/liamcain/obsidian-creases). Just put `%% fold %%` in your template where you want the content to be folded.

I'm going to close this issue since I don't think the functionality will be included in Templater core at all.
