### ISSUE TITLE
Dynamic Commands don't work for Links

### ISSUE THREAD

**Issue by momja** [SilentVoid13/Templater#528]
**Plugin informations (please complete the following information):**

-   OS: MacOS 10.15.7
-   Templater version: 1.9.9
-   Obsidian version: 0.13.19

**Describe the bug**
When I create a dynamic link like
```
[[<%+ tp.date.now("YYYY-MM-DD") %>]]
```
I would expect to be able to click the link in preview to navigate to a note for the current date (I.E. today would be "2022-01-19"), but although the link preview appears correctly, the link itself is the plain text "<%+ tp.date.now("YYYY-MM-DD") %>"

**Expected behavior**
Expect the link to be "2022-01-19", not "<%+ tp.date.now("YYYY-MM-DD") %>"

**Screenshots**
<img width="472" alt="Screen Shot 2022-01-19 at 11 05 07 AM" src="https://user-images.githubusercontent.com/3757888/150197261-5c17d0fc-1181-441b-be75-12fcfc0a78d6.png">
m.

**Comment by AB1908** [comment]
Unfortunately, that's now how this works. We need to generate a link object, akin to what dataview does. I don't know the correct API for this so let me do some testing.

**Comment by liamcain** [comment]
Hi, this is more an issue with how links work and less about Templater. I think instead of creating a link, what you want is a button that triggers the command "Open today's note." You can accomplish that with the [Buttons plugin](https://github.com/shabegom/buttons) I think.

**Comment by nixternal** [comment]
Came across this when I was experiencing a very similar thing when using Templater. I have since switched this job to dataview by doing the following in my template: I add the date frontmatter then call it inline. Have to do the string() part because link complains about inputting a date & I didn't dig deep when I figured out string fixes the issue.

---
date: {{date:YYYY-MM-DD}}
---

`= link(string(this.date))`
