### ISSUE TITLE
templater not activating

### ISSUE THREAD

**Issue by Smitty010** [SilentVoid13/Templater#650]
**Plugin information (please complete the following information):**

-   OS: Windows 11
-   Templater version: 1.12.0
-   Obsidian version: 0.14.15 (note: this is an insider build)
-   Templater settings: 
![image](https://user-images.githubusercontent.com/3760075/170888936-5b6f5b35-d5f6-4d78-817e-0d235a1c35cd.png)

No templater hotkeys or folder templates or startup templates

**Describe the bug**
I create a note called "fred"
I then hit ctrl-T to insert a template.  I end up with this.
![image](https://user-images.githubusercontent.com/3760075/170889064-fa15bc6c-9a67-4efa-8bf2-b17f8840e83f.png)

The template is:
```
# Monthly Notes - {{title}}
Month: <% tp.date.now("YYYY-MM") %> created on <% tp.date.now("dddd, MMMM Do, YYYY") %>
<< [[<% tp.date.now("YYYY-MM", "P-1M") %>]] |  [[<% tp.date.now("YYYY-MM", "P+1M") %>]] >>
```

**Expected behavior**
I expected the date references to be executed and replaced with the date.

**Screenshots**
See above

**Additional context**
I am relatively new to Obsidian.  I am a developer, so I think I'm computer literate :).  It seems like this used to work.  Maybe it's a regression in the insider build.  Or maybe I just don't understand how it's supposed to work.  

What's funny is that if I use the command in the Periodic Plugin to create the monthly note (based on the template referred to in the Periodic Plugin configuration), I believe it works (the date calls are replaced with the result).  

Let me know if I am just not understanding what is supposed to happen.  

btw--yes, there is a directory in my vault called obsidian and that directory contains the templates directory.  I know it's not a usual setup and I thought it might be confusing.  I do it so I can hide the template, asset and other directories when I am in directory view.  I have my home and a few key MOC notes in root.

**Comment by welpdx** [comment]
It seems to be working fine with me:

![img](https://i.imgur.com/Yc5HnGE.gif)

I only have templater installed in this test vault though. I am not sure what is the problem

**Comment by Smitty010** [comment]
Not sure what to say.  I do have a lot of plugins installed.

**Comment by welpdx** [comment]
Sorry for not being of help. 
Do you think you can disable plugins and see if that helps? That may help us determine if it is another plugin that caused the issue and isolate which. 

Thanks

**Comment by Smitty010** [comment]
Here's the developer log
[obsidian.md-1653863755670.log](https://github.com/SilentVoid13/Templater/files/8794410/obsidian.md-1653863755670.log)

I see one error in there thrown by the banner plugin.  But I think that's being thrown when my obsidian starts up.  I have the homepage plugin and it starts up a page with a banner on startup.  I don't see any log activity in the developer log when I do the template insert.

I'll try disabling plugins and see if I can narrow it down.  Sigh...I have so many enabled :)

**Comment by Smitty010** [comment]
I tried just disabling the banner plugin.  Still doesn't work.  I'll start doing a "binary search"

**Comment by Smitty010** [comment]
I tried the binary search and I got down to only the templater plugin and the problem still existed.  

I created a new obsidian vault called test.  The only community plugin I added is the templater.  It still doesn't work.

Here's a zip of my vault.  

[Obsidian.zip](https://github.com/SilentVoid13/Templater/files/8794575/Obsidian.zip)

The only thing I can think at this point is that maybe my obsidian installation has gotten corrupted or that there is something strange in the way I have set up the vault.

**Comment by welpdx** [comment]
[Your vault worked fine for me](https://i.imgur.com/4oQBqFg.gif). But I found the issue is when I read this:
> I then hit ctrl-T to insert a template. I end up with this.

`Ctrl + T` is the shortcut for inserting a Template. This is [the default plugin that Obsidian comes with](https://help.obsidian.md/Plugins/Templates). 

What you want to do is hit `Alt + E`, to use `Open Insert Template modal` function from [Templater](https://github.com/SilentVoid13/Templater). 


![img](https://i.imgur.com/NNGhLqW.jpeg)

It's a simple silly mistake. I think I did the exact same thing when I first transitioned from [Templates](https://help.obsidian.md/Plugins/Templates) to [Templater](https://github.com/SilentVoid13/Templater). Good thing you were so detailed and specific in your issue report, or I never would have caught that! 😄

**Comment by welpdx** [comment]
And honestly I should have caught that earlier on when I saw `{{title}}` resolved to `fred`. I haven't interact with Templates in ages and just thought it was some other plugin that resolved that. 
I should have known lol. Sorry about that

**Comment by Smitty010** [comment]
Well, that's embarrassing.  My newby-ness is showing.  Thanks for the help. 

I've tried what you say and it seems to work.  But, I'm still a little confused.  If I click on a date in the calendar control and the periodic plugin creates the daily note, then both the template variables and the templater variables get filled in.  However, if I use ctrl-t to insert a template, then only the template variables get filled in.  If I use alt-E, then only the templater variables get filled.  Is that expected behavior?

**Comment by welpdx** [comment]
That is indeed expected behaviour. It sounds like when you created a new note via periodic plugin, it triggers both the Templates and Templater plugins. 
Ctrl + T only triggers Obsidian's `Insert Template Function`.

Alt + E only triggers Templater's `Open Insert Template modal`. 

Anyways, I prefer only using the Templater plugin for consistency. Templater also opens the doors for us to use [obsidian api](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts) functions.

**Comment by Smitty010** [comment]
OK then.  I consider this issue closed.  Thanks so much for your help in clarifying this.
