### ISSUE TITLE
Function in function?

### ISSUE THREAD

**Issue by dxcore35** [SilentVoid13/Templater#709]
Hello

I would like to combine several functions into one line function, but I cannot figure out what formatting I need to use to make it work.

**Function 1:**  `<%tp.system.suggester([Yesterday, "Today"], ["Yesterday", "Today"]) %>`
**Function 2:**  `<%tp.date.yesterday("YYYY-MM-DD")%>`
**Function 3:**  `<%tp.date.now("YYYY-MM-DD-HH:MM")%>`

I would like to write it like this:

var date: `<%tp.system.suggester([Function 2, "Function 3"], ["Function 2", "Function 3"]) %>`

But I'm always getting this error:
![Screen Shot 2022-07-30 at 14 13 00](https://user-images.githubusercontent.com/7279156/181908359-efd21ffa-df9f-4eb1-bea2-acc2d362f7e3.jpg)

---

Is it possible to use this "nested functions?" Also is there any way I can use the result of this function (`var date`) and use it again in another function? For example renaming the file depending on the chose I chose?

**Comment by AB1908** [comment]
What is the use case, as in, what exactly are you looking to accomplish?

**Comment by dxcore35** [comment]
1. Open daily note
2. Get promp asking what date I want to create the new daily note:
3. Get 3 options: Yesterday, Today, Tommorow DATE
4. Depending on the option add DATE into YAML field DATE
5. Rename file to DATE

**Comment by welpdx** [comment]
You can just do this:
```js
<%* 
var yesterday = tp.date.yesterday("YYYY-MM-DD")
var today = tp.date.now("YYYY-MM-DD-HH:MM")
%>

<%* 
var input = await tp.system.suggester([yesterday, today], [yesterday, today]) 
console.log(input)
%>
```

Use `<%*` instead of `<%` to execute code. See [documentation](https://silentvoid13.github.io/Templater/commands/execution-command.html).

**Comment by dxcore35** [comment]
The problem is that:

console.log(input) should go into YAML header.
So the 3 variables will be declared after :(

```
---
date: console.log(input)
---

var yesterday = tp.date.yesterday("YYYY-MM-DD")
var today = tp.date.now("YYYY-MM-DD-HH:MM")
var input = await tp.system.suggester([yesterday, today], [yesterday, today]) 
```

**Comment by AB1908** [comment]
Why would you want a log in the yaml?

**Comment by welpdx** [comment]
ah ok, so you want to:
1. get yesterday and today's date in string
2. then have an suggested to ask what you want
3. after selection, you wan that string to appear in your yaml?

**Comment by dxcore35** [comment]
> Why would you want a log in the yaml?

I'm using the Dataview to query many things from YAML header, so I need the date also there.

**Comment by dxcore35** [comment]
> ah ok, so you want to:
> 
> 1. get yesterday and today's date in string
> 2. then have an suggested to ask what you want
> 3. after selection, you wan that string to appear in your yaml?
> 
> If this is what you want than the script that would work is this:
> 
> ```js
> <%*
> var yesterday = tp.date.yesterday("YYYY-MM-DD");
> var today = tp.date.now("YYYY-MM-DD-HH:MM");
> var input = await tp.system.suggester([yesterday, today], [yesterday, today]);
> _%>
> ---
> date: <% input %>
> ---
> ```

Thank you for your code, but for some reason it is not working for me. It throw the error.
Does it work for you?

**Comment by welpdx** [comment]
Make sure to paste the script at the very beginning of the template.
There is whitespace control: the `_` before the last `%>` would remove any whitespaces after the script so that the yaml block would be at the very top. To read more about whitespace control in templater, please see [documentation](https://silentvoid13.github.io/Templater/commands/whitespace-control.html).

<details>
           <summary style="font-size:20">Demo</summary>
           <img src="https://i.imgur.com/J5JfDN1.gif" alt="demo" />
</details>

**Comment by dxcore35** [comment]
Amazing, amazing! Thank you very much! There is so much to learn in Obsidian world.

**Comment by welpdx** [comment]
No problem, I am happy to help!

Yes there is alot to learn in general when it comes to programming. This Templater plugin is coded using Typescripts, and incorporates the [Eta Js](https://eta.js.org/) [engine](https://silentvoid13.github.io/Templater/syntax.html) so that you can write Js scripts to be executed. 

My understanding of Obsidian is that it is basically an web app like (basically a modified chrome), running html, css, js, etc...
Many of the plugins add their on ts, js scripts to add a variety of different functionality. And different themes modify css and html to change how obsidian looks. 

That's all I understand so far.  But yes, there is alot to learn when you consider programming and coding in general.

**Comment by welpdx** [comment]
By the way, can you close this issue? Just look at Green Button on the bottom right when you make a new comment that say something along the lines of "Close Issue". Thanks!

**Comment by dxcore35** [comment]
The issue was resolved perfectly! Thank you @welpdx and @AB1908 !
