### ISSUE TITLE
tp.date examples in docs are formatted incorrectly 

### ISSUE THREAD

**Issue by Aron-Polner** [SilentVoid13/Templater#852]
**Describe the bug**
Apostrophes disrupt the formatting of tp.date examples in the docs [here](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/date-module.html#tpdatenowformat-string--yyyy-mm-dd-offset-numberstring-reference-string-reference_format-string). The greed color should be shown on string input and nothing else.

**Expected behavior**
Nothing other than the string input is green in the examples.

**Screenshots**
![image](https://user-images.githubusercontent.com/85102336/193551838-d61f3443-7e51-4c0f-9b36-bb07af94d8c4.png)

**Additional context**

**Comment by Aron-Polner** [comment]
Not sure if I should add info about Templater version when creating issues I've found in the docs

**Comment by shabegom** [comment]
No need to include version. I suspect the apostrophes need to be escaped. 

Good first issue

**Comment by Zachatoo** [comment]
Should be re-opened since the change was reverted.

I did some research into this, there doesn't appear to be an escaping syntax we can use inside of codeblocks that go through mdbook -> highlight.js

I did find some information about ignoring syntax highlighting for highlight.js, but I think we'd need to write a pre-processor for mdbooks to inject ourselves in there in order to add the classes we want https://github.com/highlightjs/highlight.js/issues/2772

There's two routes I can see:
1. Write a pre-processor for mdbook to allow us to add markup to specify that some text should ignore highlighting, which our pre-processor would then be able to add classes to that text and we can style it differently.
2. Remove syntax highlighting.

**Comment by Aron-Polner** [comment]
We could also re-write the code examples. It looks good a part from the strange apostrophe stuff but are there other alternatives that could be used instead of writing a pre-processor?

**Comment by Zachatoo** [comment]
There's some other weird syntax highlighting as well, like "Date" and "with" being highlighted when they shouldn't be, as they're both keywords in JavaScript.

**Comment by Zachatoo** [comment]
Resolved by using comment syntax for describing examples.
