### ISSUE TITLE
[FEAT]Get clipboard content when insert a template

### ISSUE THREAD

**Issue by Quorafind** [SilentVoid13/Templater#86]
**Is your feature request related to a problem? Please describe.**
I need to capture my idea on Mobile, I just want to insert a template and then it contains what I copied before.

**Describe the solution you'd like**
Support something like <% CLIPBOARD %>

**Describe alternatives you've considered**
Don't know

**Additional context**
NULL

**Comment by SilentVoid13** [comment]
Hey @Quorafind, I added the new internal function `tp.file.clipboard`. 
The only problem is that it's not working on mobile. Accessing the clipboard on mobile turns out to be not easy at all. Refer to this discord chat: https://discord.com/channels/686053708261228577/817515900349448202/829764005123194900
It should work fine on desktop.
I'm leaving this issue open since it's not working on mobile yet.

**Comment by Quorafind** [comment]
Okay, thanks for your hard job!

**Comment by agnoldo** [comment]
Hello, isn't it tp.system.clipboard?

**Comment by shabegom** [comment]
https://silentvoid13.github.io/Templater/internal-functions/internal-modules/system-module.html#tpsystemclipboard
