### ISSUE TITLE
tp.file.rename with tp.file.creation_date() as argument

### ISSUE THREAD

**Issue by the-c0d3r** [SilentVoid13/Templater#95]
I'm having a problem nesting function calls. My usual workflow is to create a new untitled file, then click on templater and pick the respective template, one of which is a daily journal type note. 

And I want to make use of the rename function to automatically rename the file based on the creation date. But for some reason when I add this, I get templater error, I couldn't get the dev tools open so I cannot get the logs as well. 

```
<% tp.file.rename(tp.file.creation_date()) %>
```
I read through the docs, there is no mention of nested calls or defining of new variables. 
Is this supported?

**Comment by the-c0d3r** [comment]
Full template file looks like this. 

```
---
creation date: <% tp.file.creation_date() %>
modification date: <% tp.file.creation_date("dddd Do MMMM YYYY HH:mm:ss") %>
---

<% tp.file.rename(tp.file.creation_date()) %>

# <% tp.file.title %>

<< [[<% tp.date.now("YYYY-MM-DD", -1) %>]] | [[<% tp.date.now("YYYY-MM-DD", 1) %>]] >>

<% tp.web.daily_quote() %>

<% tp.user.weather() %>


## TODOs
- 

## Completed

## Note

```

Side question: Is there any ways to make obsidian prompt for template selection, when using the command pallet to execute "open today's daily note"?

**Comment by SilentVoid13** [comment]
Hey @the-c0d3r, this is supported. The problem you're encountering is that the default format for `tp.file.creation_date` is `YYYY-MM-DD HH:mm`.
Obsidian does not allow the following characters in the filename: `\ / :`, you have to change the format for `tp.file.creation_date` to something that does include `:`. 

Tell me if this works if you change that.

About your side question: There is currently no way to open the modal for template selection when opening a new daily note, it opens the daily note with what the template defined in the daily note core plugin settings. 
I don't think I'll add that feature to Templater, because that would mean hijacking another plugin, and I don't like the idea.

**Comment by the-c0d3r** [comment]
Hi @SilentVoid13 , thank you for the solution. It works for me. 
And thanks a lot for creating this awesome plugin.
