### ISSUE TITLE
Tp.File.Cursor for values 100 and greater

### ISSUE THREAD

**Issue by roc26** [SilentVoid13/Templater#956]
I'm sure this is expected behavior, as it may have not been anticipated as a need, but is there any way for me to tweak Templater so it'll support commands such as 
<% tp.file.cursor(112) %>  

My shortcut key which I've assigned to jump to the next position doesn't work beyond 99. 

Any workaround or custom code I could use would be much appreciated! Thank you.

**Comment by Zachatoo** [comment]
Found the culprit.

```js
const cursor_regex = new RegExp(
    "<%\\s*tp.file.cursor\\((?<order>[0-9]{0,2})\\)\\s*%>",
    "g"
);
```

Looks like the code is limited to only two characters `{0,2}` which is why you can only go up to 99.

Do you really have that many cursors in your template? I am genuinely impressed. Regardless, I've put up a PR to allow as many cursors as you want, if you want that fixed now you could pull down and build my branch and use that for now.
