### ISSUE TITLE
Mistyped example

### ISSUE THREAD

**Issue by hesoyamimi** [SilentVoid13/Templater#995]
Found a mistyped tp.system.suggester [example](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/system-module.html#examples) 

```
<%*
const execution_value = await tp.system.suggester(["Yes", "No"], ["true", "false"])
%>
Are you using Execution Commands: <%*  tR + execution_value %>
```

Does not print the value of execution_value. But when add = sign accordingly 

```
<%*
let execution_value = await tp.system.suggester(["Yes", "No"], ["true", "false"])
%>
Are you using Execution Commands: <%*  tR += execution_value %>
```

Substitution works fine after an addition.  It that a mistype?

UPD: Just tried again to define a execution_value variable using const and it worked. So strange

**Comment by Zachatoo** [comment]
Looks like the only difference you had is that you changed `const` to `let`.

The example is fine. However, if you declare the same variable twice in one script with `const` it will not work, as variables created using `const` cannot be recreated or reassigned. `let` variables can be reassigned.

It's likely you had two `const execution_value = ` in the same script, which would cause that issue. A good practice would be to have all of your variable names be unique, don't redeclare the same variable more than once.

**Comment by holroy** [comment]
> Looks like the only difference you had is that you changed `const` to `let`.
> 
> The example is fine.

I think what he eludes to is that in general if you want output from a javascript execution block you need to type `tR += execution_value`. In the special case of that being the only thing returned you can do the `<%* tR + execution_value %>` since that's the only statement in that block, and it's returned by default.

Then again, that example should probably be written as just `<% execution_value %>` (if I'm not mistaken), with no need to re-introduce the javascript execution block or the `tR` variable. 

The reason I came in here today, was actually to post the same kind of report on this topic. It's kind of unclear, even though it does work.

**Comment by Zachatoo** [comment]
Fixed the example to use `+=` instead of `=`

holroy is correct, you could either to `<%* tR += execution_value %>` or `<% execution_value %>`
